const questionDatabase = [
    // --- LATIHAN DERET ---
    { id: "qp_s1", pool: "practice", type: "series", difficulty: 1, content: { sequence: [2, 4, 6, 8, "?"], options: [10, 12, 14, 16] }, correctAnswer: 10, hints: ["Perhatikan selisih antar angka."], explanation: { text: "Deret aritmatika dasar (+2)." } },
    { id: "qp_s2", pool: "practice", type: "series", difficulty: 2, content: { sequence: [3, 9, 27, 81, "?"], options: [162, 243, 300, 324] }, correctAnswer: 243, hints: ["Uji rasio perkalian."], explanation: { text: "Deret geometri dasar (x3)." } },
    { id: "qp_s3", pool: "practice", type: "series", difficulty: 3, content: { sequence: [1, 4, 9, 16, 25, "?"], options: [30, 32, 36, 49] }, correctAnswer: 36, hints: ["Ini adalah pola bilangan kuadrat."], explanation: { text: "Bilangan kuadrat (1², 2², 3², 4², 5², 6²)." } },
    
    // --- LATIHAN SILOGISME ---
    { id: "qp_sy1", pool: "practice", type: "syllogism", difficulty: 1, content: { premises: ["Semua A adalah B.", "C adalah A."], options: ["C bukan B.", "C adalah B.", "B adalah C.", "Sebagian C adalah B."] }, correctAnswer: "C adalah B.", hints: ["Jika C ada di dalam himpunan A, dan A ada di dalam B..."], explanation: { text: "Silogisme deduktif langsung." } },
    { id: "qp_sy2", pool: "practice", type: "syllogism", difficulty: 3, content: { premises: ["Semua insinyur sipil memahami mekanika.", "Beberapa konsultan adalah insinyur sipil."], options: ["Semua konsultan memahami mekanika.", "Beberapa konsultan memahami mekanika.", "Tidak ada konsultan yang memahami mekanika.", "Tidak dapat ditarik kesimpulan."] }, correctAnswer: "Beberapa konsultan memahami mekanika.", hints: ["Premis partikular ('Beberapa') biasanya menghasilkan kesimpulan partikular."], explanation: { text: "Silogisme kategori tingkat 3 (Modus AAA-I/Partikular Afirmatif)." } },
    
    // --- ASESMEN HARIAN (CAMPURAN) ---
    { id: "qm_1", pool: "assessment", type: "series", difficulty: 2, content: { sequence: [5, 7, 11, 19, 35, "?"], options: [55, 61, 67, 72] }, correctAnswer: 67, explanation: { text: "Selisih angkanya adalah 2, 4, 8, 16. Selisih berikutnya 32. 35 + 32 = 67." } },
    { id: "qm_2", pool: "assessment", type: "series", difficulty: 3, content: { sequence: [2, 5, 11, 23, "?"], options: [45, 47, 48, 51] }, correctAnswer: 47, explanation: { text: "Pola ganda: Angka sebelumnya dikali 2, ditambah 1 (x2 + 1)." } },
    { id: "qm_3", pool: "assessment", type: "syllogism", difficulty: 2, content: { premises: ["Jika proyek selesai, bonus cair.", "Proyek selesai."], options: ["Bonus cair.", "Bonus tidak cair.", "Proyek ditunda.", "Tidak ada kesimpulan."] }, correctAnswer: "Bonus cair.", explanation: { text: "Modus Ponens (p → q, p, maka q)." } },
    { id: "qm_4", pool: "assessment", type: "syllogism", difficulty: 4, content: { premises: ["Semua logam memuai jika dipanaskan.", "Emas adalah logam."], options: ["Emas memuai jika dipanaskan.", "Emas tidak memuai.", "Sebagian emas memuai.", "Emas bukan logam."] }, correctAnswer: "Emas memuai jika dipanaskan.", explanation: { text: "Deduksi Silogisme Universal." } },
    { id: "qm_5", pool: "assessment", type: "series", difficulty: 4, content: { sequence: [1, 2, 6, 24, 120, "?"], options: [360, 480, 720, 840] }, correctAnswer: 720, explanation: { text: "Pola Faktorial. Pengali bertambah: x2, x3, x4, x5, x6. 120 x 6 = 720." } }
];